name: Build NXGS Gaming devel flatpak x64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build NXGS Gaming devel flatpak_x64
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          path: 'chiaki-ng'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          git \
          flatpak \
          flatpak-builder

      - name: Setup Flatpak Builder Environment
        run: |
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install org.kde.Sdk//6.9 -y
          flatpak install org.kde.Platform//6.9 -y
          flatpak install io.qt.qtwebengine.BaseApp//6.9 -y
          flatpak update --appstream --assumeyes

      - name: Build Flatpak package
        working-directory: chiaki-ng
        run: |
          flatpak-builder --repo=nxgs-gaming-devel --force-clean build-dir scripts/flatpak/chiaki4deck-devel.yaml

      - name: Bundle Flatpak app
        working-directory: chiaki-ng
        run: |
          flatpak build-bundle nxgs-gaming-devel nxgs-gaming-devel-x64.flatpak com.nxgsstudio.nxgsgaming.Devel --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo
          flatpak build-bundle nxgs-gaming-devel --runtime nxgs-gaming-devel-x64-debug.flatpak com.nxgsstudio.nxgsgaming.Devel.Debug --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo
      - name: Upload NXGS Gaming Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nxgs-gaming-devel-x64.flatpak
          path: chiaki-ng/nxgs-gaming-devel-x64.flatpak
          if-no-files-found: error
          retention-days: 1
      - name: Upload NXGS Gaming Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nxgs-gaming-devel-x64-debug.flatpak
          path: chiaki-ng/nxgs-gaming-devel-x64-debug.flatpak
          if-no-files-found: error
          retention-days: 1
