name: Build NXGS Gaming macOS

on:
  workflow_dispatch:

jobs:
  build-mac_x64:
    name: Build macOSX x86_64 version
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install protobuf
        run: |
          pip3 install --user 'protobuf>=5,<6' --break-system-packages

      - name: Install brew dependencies
        run: |
          brew update
          brew install qt@6 ffmpeg pkgconfig opus openssl cmake ninja nasm protobuf@29 speexdsp libplacebo wget python-setuptools json-c miniupnpc libevent || true

      - name: Install sdl2-compat
        run: |
          sudo INSTALL_PREFIX=/usr/local scripts/build-sdl2-compat.sh
          sudo cp /usr/local/lib/pkgconfig/sdl2-compat.pc /usr/local/lib/pkgconfig/sdl2.pc

      - name: Configure NXGS Gaming
        run: |
          cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCHIAKI_ENABLE_CLI=OFF -DCHIAKI_ENABLE_STEAMDECK_NATIVE=OFF -DCMAKE_PREFIX_PATH="$(brew --prefix)/opt/@openssl@3;$(brew --prefix)/opt/qt@6;$(brew --prefix)/opt/protobuf@29"

      - name: Build NXGS Gaming
        run: |
          export CPATH=$(brew --prefix)/opt/ffmpeg/include
          cmake --build build --config Release --clean-first --target chiaki

      - name: Deploy NXGS Gaming
        run: |
          rm -rf "NXGS Gaming.app" nxgs-gaming.dmg
          cp -a build/gui/chiaki.app "NXGS Gaming.app"
          cp scripts/qtwebengine_import.qml gui/src/qml/
          $(brew --prefix)/opt/qt@6/bin/macdeployqt "NXGS Gaming.app" -qmldir="$PWD/gui/src/qml" -libpath=$(brew --prefix)/lib
          mkdir -p "NXGS Gaming.app"/Contents/Resources/vulkan/icd.d
          wget https://github.com/KhronosGroup/MoltenVK/releases/download/v1.2.9/MoltenVK-macos.tar && tar xf MoltenVK-macos.tar
          cp MoltenVK/MoltenVK/dylib/macOS/* "NXGS Gaming.app"/Contents/Resources/vulkan/icd.d
          $(brew --prefix)/opt/qt@6/bin/macdeployqt "NXGS Gaming.app" -qmldir="$PWD/gui/src/qml" -libpath=$(brew --prefix)/lib
          if [[ -d "NXGS Gaming.app"/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app ]]
          then
            ln -s ../../../../../../../Frameworks "NXGS Gaming.app"/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents
          fi
          cp /usr/local/lib/libSDL3.dylib "NXGS Gaming.app"/Contents/MacOS/libSDL3.dylib
          cp /usr/local/lib/libSDL2-2.0.0.dylib "NXGS Gaming.app"/Contents/MacOS/libSDL2-2.0.0.dylib
          install_name_tool -id @executable_path/libSDL3.dylib "NXGS Gaming.app"/Contents/MacOS/libSDL3.dylib
          install_name_tool -id @executable_path/libSDL2-2.0.0.dylib "NXGS Gaming.app"/Contents/MacOS/libSDL2-2.0.0.dylib
          install_name_tool -change /usr/local/lib/libSDL3.dylib @executable_path/libSDL3.dylib "NXGS Gaming.app"/Contents/MacOS/libSDL2-2.0.0.dylib || true
          install_name_tool -change @rpath/libSDL3.dylib @executable_path/libSDL3.dylib "NXGS Gaming.app"/Contents/MacOS/libSDL2-2.0.0.dylib || true
          install_name_tool -change /opt/homebrew/lib/libSDL3.dylib @executable_path/libSDL3.dylib "NXGS Gaming.app"/Contents/MacOS/libSDL2-2.0.0.dylib || true
          install_name_tool -change /usr/local/lib/libSDL2-2.0.0.dylib @executable_path/libSDL2-2.0.0.dylib "NXGS Gaming.app"/Contents/MacOS/chiaki || true
          install_name_tool -change @rpath/libSDL2-2.0.0.dylib @executable_path/libSDL2-2.0.0.dylib "NXGS Gaming.app"/Contents/MacOS/chiaki || true
          install_name_tool -change /opt/homebrew/lib/libSDL2-2.0.0.dylib @executable_path/libSDL2-2.0.0.dylib "NXGS Gaming.app"/Contents/MacOS/chiaki || true
          ln -s libvulkan.1.dylib "NXGS Gaming.app"/Contents/Frameworks/vulkan
          codesign --force --entitlements gui/entitlements.xml --deep --sign - "NXGS Gaming.app"
          rm -f nxgs-gaming.dmg
          hdiutil create -srcfolder "NXGS Gaming.app" nxgs-gaming.dmg
          codesign --force --entitlements gui/entitlements.xml --deep --sign - nxgs-gaming.dmg

      - name: Upload NXGS Gaming Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nxgs-gaming-macos_x86_64-Release
          path: nxgs-gaming.dmg
          if-no-files-found: error
          retention-days: 7

  build-mac_arm64:
    name: Build macOSX arm64 version
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install protobuf
        run: |
          pip3 install --user 'protobuf>=5,<6' --break-system-packages
      - name: Install brew dependencies
        run: |
          brew update
          brew install qt@6 ffmpeg pkgconfig opus openssl cmake ninja nasm protobuf@29 speexdsp libplacebo wget python-setuptools json-c miniupnpc libevent

      - name: Install sdl2-compat
        run: |
          sudo INSTALL_PREFIX=/usr/local scripts/build-sdl2-compat.sh
          sudo cp /usr/local/lib/pkgconfig/sdl2-compat.pc /usr/local/lib/pkgconfig/sdl2.pc

      - name: Configure NXGS Gaming
        run: |
          cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCHIAKI_ENABLE_CLI=OFF -DCHIAKI_ENABLE_STEAMDECK_NATIVE=OFF -DCMAKE_PREFIX_PATH="$(brew --prefix)/opt/@openssl@3;$(brew --prefix)/opt/qt@6;$(brew --prefix)/opt/protobuf@29"

      - name: Build NXGS Gaming
        run: |
          export CPATH=$(brew --prefix)/opt/ffmpeg/include
          cmake --build build --config Release --clean-first --target chiaki

      - name: Deploy NXGS Gaming
        run: |
          rm -rf "NXGS Gaming.app" nxgs-gaming.dmg
          cp -a build/gui/chiaki.app "NXGS Gaming.app"
          echo "import QtWebEngine; WebEngineView {}" > "$PWD/gui/src/qml/qtwebengine_import.qml"
          $(brew --prefix)/opt/qt@6/bin/macdeployqt "NXGS Gaming.app" -qmldir="$PWD/gui/src/qml" -libpath=$(brew --prefix)/lib
          mkdir -p "NXGS Gaming.app"/Contents/Resources/vulkan/icd.d
          wget https://github.com/KhronosGroup/MoltenVK/releases/download/v1.2.9/MoltenVK-macos.tar && tar xf MoltenVK-macos.tar
          cp MoltenVK/MoltenVK/dylib/macOS/* "NXGS Gaming.app"/Contents/Resources/vulkan/icd.d
          $(brew --prefix)/opt/qt@6/bin/macdeployqt "NXGS Gaming.app" -qmldir="$PWD/gui/src/qml" -libpath=$(brew --prefix)/lib
          if [[ -d "NXGS Gaming.app"/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app ]]
          then
            ln -s ../../../../../../../Frameworks "NXGS Gaming.app"/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents
          fi
          cp /usr/local/lib/libSDL3.dylib "NXGS Gaming.app"/Contents/MacOS/libSDL3.dylib
          cp /usr/local/lib/libSDL2-2.0.0.dylib "NXGS Gaming.app"/Contents/MacOS/libSDL2-2.0.0.dylib
          install_name_tool -id @executable_path/libSDL3.dylib "NXGS Gaming.app"/Contents/MacOS/libSDL3.dylib
          install_name_tool -id @executable_path/libSDL2-2.0.0.dylib "NXGS Gaming.app"/Contents/MacOS/libSDL2-2.0.0.dylib
          install_name_tool -change /usr/local/lib/libSDL3.dylib @executable_path/libSDL3.dylib "NXGS Gaming.app"/Contents/MacOS/libSDL2-2.0.0.dylib || true
          install_name_tool -change @rpath/libSDL3.dylib @executable_path/libSDL3.dylib "NXGS Gaming.app"/Contents/MacOS/libSDL2-2.0.0.dylib || true
          install_name_tool -change /opt/homebrew/lib/libSDL3.dylib @executable_path/libSDL3.dylib "NXGS Gaming.app"/Contents/MacOS/libSDL2-2.0.0.dylib || true
          install_name_tool -change /usr/local/lib/libSDL2-2.0.0.dylib @executable_path/libSDL2-2.0.0.dylib "NXGS Gaming.app"/Contents/MacOS/chiaki || true
          install_name_tool -change @rpath/libSDL2-2.0.0.dylib @executable_path/libSDL2-2.0.0.dylib "NXGS Gaming.app"/Contents/MacOS/chiaki || true
          install_name_tool -change /opt/homebrew/lib/libSDL2-2.0.0.dylib @executable_path/libSDL2-2.0.0.dylib "NXGS Gaming.app"/Contents/MacOS/chiaki || true
          ln -s libvulkan.1.dylib "NXGS Gaming.app"/Contents/Frameworks/vulkan
          codesign --force --entitlements gui/entitlements.xml --deep --sign - "NXGS Gaming.app"
          rm -f nxgs-gaming.dmg
          hdiutil create -srcfolder "NXGS Gaming.app" nxgs-gaming.dmg
          codesign --force --entitlements gui/entitlements.xml --deep --sign - nxgs-gaming.dmg

      - name: Upload NXGS Gaming Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nxgs-gaming-macos_arm64-Release
          path: nxgs-gaming.dmg
          if-no-files-found: error
          retention-days: 7
